spring:
 application:
  name: secryptech-task-service
 datasource:
  url: jdbc:mysql://localhost:3306/tasks
  username: root
  password: mame
 jpa:
  
  generate-ddl: true
  database-platform: org.hibernate.dialect.MySQL5Dialect
  hibernate:
   ddl-auto: update
server:
 port: 8084

